# Configuration file for stitcher

# Path to Libre Office executable. Multiple paths can be specified, first valid will be used.
# If no path is valid or none exists, conversion of document formats is disabled.
libreoffice_path = ["%PROGRAMFILES(X86)%\\LibreOffice\\program\\soffice.exe", "%PROGRAMFILES%\\LibreOffice\\program\\soffice.exe"]

# Path to the output folder. May contain '~' and $ variables.If not specified, current working directory will be used.
# output_folder = ~

# Margin to be used when adding images. Horizontal then vertical dimension, separated by 'x'
margin = "0.0pt x 0.0pt"

# Page size to be used when adding images. Horizontal then vertical dimension, separated by 'x'.
# Can also specify common paper sizes, like 'A4'
page_size = "595pt x 842pt"
